### ISSUE TITLE
cannot import name 'AccountRead'

### ISSUE THREAD

**Issue by 92bd4** [financelurker/cryptocom-csv-firefly-iii#1]
Hi, I have built your Docker image on my raspberry pi 4 and it refuses to start for some reason.

Any idea why https://github.com/financelurker/cryptocom-csv-firefly-iii/blob/main/src/main.py#L7 fails?

Logs:
```bash
$ docker logs firefly_csv
Traceback (most recent call last):
  File "/opt/cryptocom-csv-firefly-iii/src/main.py", line 7, in <module>
    from firefly_iii_client import AccountRead
ImportError: cannot import name 'AccountRead' from 'firefly_iii_client' (/usr/local/lib/python3.9/site-packages/firefly_iii_client/__init__.py)
```

Docker-compose file in case it matters:
```yaml
services:

  firefly:
    image: fireflyiii/core
    env_file: ${DOCKERCONFIG}/firefly/.env
    networks:
      firefly_web:
      firefly:

  firefly_csv:
    image: built_cryptocom-csv-firefly-iii
    environment:
      IMPORT_INTERVAL: 300
      FIREFLY_III_ACCESS_TOKEN: "XXXXX"
      FIREFLY_III_URL: http://firefly:8080
      DEBUG: 123
    volumes:
      - ${DATA}/firefly_cdc_csv/import:/var/cryptocom-csv-firefly-iii/csv-to-import
      - ${DATA}/firefly_cdc_csv/history:/var/cryptocom-csv-firefly-iii/csv-import-history
      - ${DATA}/firefly_cdc_csv/failed:/var/cryptocom-csv-firefly-iii/csv-import-failed
    networks:
      firefly:
```

Many thanks :)
